In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [1]:
arr

NameError: name 'arr' is not defined

In [2]:
arr = np.arange(5)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
arr = np.arange(5)

In [5]:
arr

array([0, 1, 2, 3, 4])

In [6]:
np.save('myarray',arr)

In [7]:
#create a 10-point long array
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#load a file, have to call the extension "".npy"
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [10]:
arr1 = np.load('myarray.npy')

In [11]:
arr1

array([0, 1, 2, 3, 4])

In [12]:
arr2 = arr
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#save a zip file, extension ".npz"
np.savez('ziparray.npz', x=arr1, y=arr2)


In [14]:
#load the zip file
archive_array = np.load('ziparray.npz')

In [15]:
#load the "x" array in the zip file
archive_array['x']

array([0, 1, 2, 3, 4])

In [16]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#save and load a text file
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#save the matrix as a text file with the delimiter (which separates the values). in this case delimiter is "comma separator"
np.savetxt('mytextarray.txt',arr,delimiter=',')

In [19]:
#load a ".txt" file: method is np.loadtxt()
arr = np.loadtxt('mytextarray.txt',delimiter=',')

In [20]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
arr = np.loadtxt('mytextarray.txt')
arr

ValueError: could not convert string to float: '1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00'