In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# WE can "randomly reorder" (permutate) a Series, or the rows in a DataFrame

#Let's take a look
#create a 4x4 dframe
dframe = DataFrame(np.arange(4*4).reshape(4,4))
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [5]:
#Create an array with a random perumation of 0,1,2,3
#random order of an array of 4 values
blender = np.random.permutation(4)

In [6]:
blender

array([3, 1, 2, 0])

In [7]:
# Now permutate the dframe based on the blender
dframe.take(blender)
# new order of rows in dframe: index-3 row, index-1 row, index-2 row, index-0 row

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

In [8]:
# Now what if we want permuations WITH replacement

# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3
box = np.array([1,2,3])

# Now lets create a "random permuation WITH replacement" using randint
# low to high => 0 to the length of the box. Size = how many times I'll pick from the above box
shaker = np.random.randint(0, len(box), size  = 10)
#return random integers from low (=0) to high (=length of box)
#return a range of 10 random integers from 0 to 2

In [12]:
#return a range of 10 random integers from 0 to 2
shaker


array([2, 2, 2, 1, 2, 0, 1, 0, 1, 0])

In [13]:
#Now lets grab form the box
#pass the take method on the box, argument = shaker
hand_grabs = box.take(shaker)

In [14]:
hand_grabs
#simulation of taking a marble, seeing what number the marble is, write down the number. Repeat this procedure 10 times

array([3, 3, 3, 2, 3, 1, 2, 1, 2, 1])

In [ ]:
#grab the index-2 marble, grab the index-2 marble, grab the index-2 marble, grab the 0-index marble, etc.
#value 3 corresponds to index-2 marble