In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# Concatenate along axis 1 (axis Oy/column)

np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# Concatenate along axis 0 (axis Ox/row)


np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# Now let's see how this works in pandas
# Lets create two Series with no overlap
ser1 = Series([0,1,2],index=['T','U','V'])

In [7]:
ser2 = Series([3,4],index=['X','Y'])

In [8]:
#Now let use concat (default is axis=0 [axis Ox, ROW])
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
# Now passing along another axis (not 0) will produce a DataFrame
pd.concat([ser1,ser2],axis=1)
#column are automatically named: 0,1,etc.

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
# We can specify which specific axes to be used
pd.concat([ser1,ser2],axis=1,join_axes=[['T','U','V']])
# U, V are from series1; V IS from series2

0   1
T  0 NaN
U  1 NaN
V  2 NaN

In [13]:
# Lets say we wanted to add markers.keys to the concatenation result

# WE can do this with a hierarchical index
pd.concat([ser1,ser2],keys=['cat1','cat2'])
#cat 1 is series1; cat2 is series2

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
#Lastly, everything works similarly for DataFrames (in Pandas)
#create 2 dataframes
#pass columnn names for each dataframe
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Q','X','Y'])

In [15]:
#Concat on DataFrame
pd.concat([dframe1,dframe2])

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  


Q         X         Y         Z
0       NaN -2.919043 -1.128259 -1.506277
1       NaN  1.582653 -0.688653  0.227953
2       NaN  1.165673 -1.473055 -1.952724
3       NaN  0.537191  0.434712  1.276374
0  2.320300  0.323381 -0.781136       NaN
1 -0.920168 -0.555995  0.667849       NaN
2  1.069590  1.136632  0.819547       NaN

In [16]:
#If we dont care about the index info and just awnt to make a complete DataFrame, just use ignore_index
pd.concat([dframe1,dframe2],ignore_index=True)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  


Q         X         Y         Z
0       NaN -2.919043 -1.128259 -1.506277
1       NaN  1.582653 -0.688653  0.227953
2       NaN  1.165673 -1.473055 -1.952724
3       NaN  0.537191  0.434712  1.276374
4  2.320300  0.323381 -0.781136       NaN
5 -0.920168 -0.555995  0.667849       NaN
6  1.069590  1.136632  0.819547       NaN

In [ ]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'