In [1]:
import numpy as np

In [4]:
#call a range of 11 points
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#take squareroots of every value in an array

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
#take the exponential of every value in an array
#meaning: e^point value

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
# first item: e^0 = 1

In [8]:
# create a random array.
#call random from the numpy library
#randn: call a random normal distribution

A = np.random.randn(10)
A

array([-1.62622632, -0.38264287,  0.86837371, -0.78230107,  0.63528638,
        0.21855044,  1.79896975, -0.4273585 , -0.62725777, -0.37371305])

In [9]:
B = np.random.randn(10)
B

array([ 0.61783526, -0.10709951,  2.58318072, -0.40131286,  1.20051842,
        0.26124113, -0.12936901,  0.93056765, -0.86374416,  1.82838756])

In [10]:
# Binary functions (e.g. adding matrices)
np.add(A,B)

array([-1.00839106, -0.48974238,  3.45155444, -1.18361394,  1.8358048 ,
        0.47979157,  1.66960074,  0.50320915, -1.49100193,  1.4546745 ])

In [11]:
#find the max or min between 2 arrays
np.maximum(A,B)

array([ 0.61783526, -0.10709951,  2.58318072, -0.40131286,  1.20051842,
        0.26124113,  1.79896975,  0.93056765, -0.62725777,  1.82838756])

In [12]:
#extensive list of all the universal array functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
#call web browser to open that website link
webbrowser.open(website)

True