In [1]:
import numpy as np

In [9]:
#a range with values starting at Zero to the value before 11, implied step = 1
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arrX = np.arange (0,3,5)
arrX

array([0])

In [4]:
arrY = np.arange(1,8,2)
arrY

array([1, 3, 5, 7])

In [5]:
arrZ = np.arange (1,7,2)
arrZ

array([1, 3, 5])

In [6]:
arr[8]

8

In [8]:
#ouput elements with index 1 to the index before 5
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
#for all indexes from 0 through the index before 5, set them to 100
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [14]:
# set all the emenents in this array to 99
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
# if you grab slices of your array, all of these changes also occur in the original array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
#explicitly make a copy of the array. Otherwise you are making changes to the original array
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# indexing in a 2 dimesional array
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
# view row with index 1
arr_2d[1]

array([20, 25, 30])

In [20]:
# view index-0 row
arr_2d[0]

array([ 5, 10, 15])

In [21]:
# view value at index-1 row and index-0 column
arr_2d[1][0]

20

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
# take a slice (a 2x2 matrix) of the original 3x3 matrix
# row: index 0, 1 => rows before 2
# column: index 1,2 => columns starting at 1
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
# view index-2 row of the 2-dimensional array
arr_2d[2]

array([35, 40, 45])

In [26]:
# create a new 10x10 matrix filled with zeros
new2d_array = np.zeros((10,10))
new2d_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
#these values are all floats (notice the decimal points)

#get length of the first row in the matrix
arr_length = new2d_array.shape[1]

In [28]:
arr_length

10

In [29]:
arrQ = np.zeros((3,5))
arrQ

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
arrQ_length = arrQ.shape[1]

In [31]:
arrQ_length

5

In [32]:

for i in range(arr_length):    #for every i in range of 0 to 10
    #all elements of the i-index row will be equal to 1
    new2d_array[i] = 1

In [33]:
new2d_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
for i in range(arr_length):    #for every i in range of 0 to 10
    #all elements of the i-index row will be equal to the count number"i"
    new2d_array[i] = i

In [35]:
new2d_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [37]:
# fancy indexing

# view rows with index 2,4,6,8 of the matrix
new2d_array[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [38]:
# you can also view random rows of the matrix, in any order
new2d_array[[6,2,4,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])